<tr>
    <td>
        <?= htmlentities( $gallery->getTitle() ) ?>
        <div class="list-table-actions">
            <span class="edit">
                <a  href="gallery-edit_id_<?= $gallery->getId() ?>">Modifier</a> |
            </span>
            <span class="supp">
                <button id="supp_id_<?= htmlentities( $gallery->getId() ) ?>" type="text" >Supprimer</button>
            </span>
        </div>
    </td>
    <td><img src="<?= htmlentities( $gallery->getImage() ) ?>" alt="<?= htmlentities( $gallery->getTitle() ) ?>"></td>
    <td><?= htmlentities( $gallery->getArticle()->getTitle() ) ?></td>
    <td><?= sql_2_date( htmlentities( $gallery->getDate() ) ) ?></td>
</tr>