
<h1>Gestion des lettres de nouvelles
    <a class="button button-normal" href="newsletter-edit_id_0">Nouvel lettre</a>
</h1>

<table class="list-table">
    <thead>
        <tr>
            <th>Catégorie</th>
            <th>Titre</th>
            <th>Date</th>
        </tr>
    </thead>

    <tbody>
        <?php require('apps/admin/newsletter.php'); ?>
    </tbody>
</table>
<?php require('apps/confirm-box.php'); ?>
