<h1>Edition feuille</h1>
<form method="POST" class="edit" enctype="multipart/form-data">
    <input type="hidden" id="id" name="id" value="<?= htmlentities( $id ) ?>">
    <input type="hidden" id="image" name="image"  value="<?= htmlentities( $image ) ?>">
    <input type="hidden" id="video" name="video"  value="<?= htmlentities( $video ) ?>">

    <p>
        <label for="title">Titre</label>
        <input type="text" id="title" name="title" placeholder="Titre*" value="<?= htmlentities( $title ) ?>">
    </p>
    <p>
        <label for="content">Contenu</label>
        <textarea id="content" name="content" placeholder="Contenu*"><?= htmlentities( $content) ?></textarea>
    </p>

    <p>
        <label for="video_upload">Vidéo</label>
        <input type="file" id="video_upload" name="video_upload">
        <button id="button_video_upload" type="submit" class="button button-normal" name="action" value="upload-video">Ajouter la video</button>
    </p>
    <p class="edit-video">
        <label for="video_name"><span>Nom</span></label>
        <input type="text" id="video_name"  placeholder="" value="<?= basename( htmlentities( $video ) ) ?>" disabled />
        <button id="button_video_supp" type="text" class="button button-normal">Supprimer la video</button>
    </p>
    <p class="edit-video">
        <label><span>Aperçu</span></label>
        <video controls>
            <source id="video_previous" src="<?= htmlentities( $video ) ?>" />
        </video>
    </p>

    <p>
        <label for="image_upload">Image</label>
        <input type="file" id="image_upload" name="image_upload">
        <button id="button_image_upload" type="submit" class="button button-normal" name="action" value="upload-image">Ajouter l'image</button>
    </p>
    <p class="edit-image">
        <label for="image_name"><span>Nom</span></label>
        <input type="text" id="image_name"  placeholder="" value="<?= basename( htmlentities( $image ) ) ?>" disabled />
        <button id="button_image_supp" type="text" class="button button-normal">Supprimer l'image</button>
    </p>
    <p class="edit-image">
        <label><span>Aperçu</span></label>
        <img id="image_previous" src="<?= htmlentities( $image ) ?>" alt="<?= basename( htmlentities( $image ) ) ?>"/>
    </p>

    <p>
        <label for="newsletter">Afficher les lettres de nouvelles</label>
        Oui <input type="radio" id="newsletter" name="newsletter" value="1" <?= checked( $newsletter, 1 ) ?>>
        Non <input type="radio" name="newsletter" value="0" <?= checked( $newsletter, 0 ) ?>>
    </p>
    <p>
        <label for="report">Afficher les reports</label>
        Oui <input type="radio" id="report" name="report" value="1" <?= checked( $report, 1 ) ?>>
        Non <input type="radio" name="report" value="0" <?= checked( $report, 0 ) ?>>
    </p>

    <div class="edit-button">
        <button type="submit" class="button button-normal" name="action" value="<?= $sheet_action ?>">Sauvegarder</button>
    </div>
</form>