
<h1>Gestion des feuilles
    <a class="button button-normal" href="sheet-edit_id_0">Nouvelle feuille</a>
</h1>

<table class="list-table">
    <thead>
        <tr>
            <th>Titre</th>
            <th title="Voir 'Gestion des menus.'">Ordre d'affichage</th>
            <th>Lettre de nouvelles</th>
            <th>Rapport</th>
            <th>Date</th>
        </tr>
    </thead>

    <tbody>
        <?php require('apps/admin/sheet.php'); ?>
    </tbody>
</table>
<?php require('apps/confirm-box.php'); ?>
