<tr>
    <td>
        <?= htmlentities( $sheet->getTitle() ) ?>
        <div class="list-table-actions">
            <span class="edit">
                <a  href="sheet-edit_id_<?= htmlentities( $sheet->getId() ) ?>">Modifier</a> |
            </span>
            <span class="supp">
                <button id="supp_id_<?= htmlentities( $sheet->getId() ) ?>" type="text" >Supprimer</button>
            </span>
        </div>
    </td>
    <td><?= display_menu_order( htmlentities( $sheet->getMenuOrder() ) ) ?></td>
    <td><?= display_yes_no( htmlentities( $sheet->getNewsletter() ) ) ?></td>
    <td><?= display_yes_no( htmlentities( $sheet->getReport() ) ) ?></td>
    <td><?= sql_2_date( htmlentities( $sheet->getDate() ) ) ?></td>
</tr>