<li class="menu-has-children">
    <a class="<?= side_menu_select( array( 'reports', 'report-edit' ), $page ); ?>" href="reports">Rapport</a>
    <ul class="<?= side_menu_sub_menu_display( array( 'reports', 'report-edit' ), $page ); ?>">
        <li><a class="<?= side_menu_sub_menu_select( 'reports', $page ); ?>" href="reports">Tous les rapports</a></li>
        <li><a class="<?= side_menu_sub_menu_select( 'report-edit', $page ); ?>" href="report-edit_id_0">Nouveau rapport</a></li>
    </ul>
</li>