<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="<?= CSS_PATH ?>/style-admin.css" />
        <script src="<?= JS_PATH ?>/jquery-2.2.3.min.js"></script>
        <script src="<?= JS_PATH ?>/admin/main.js"></script>
        <title>Admin <?= htmlentities(  $SETTINGS->findByName('short-name')->getValue() ) ?></title>
    </head>

    <body>

        <?php require("apps/admin/header.php"); ?>
        <?php require("apps/admin/content.php"); ?>
        <?php require("apps/admin/footer.php"); ?>

    </body>
</html>