<div class="contact">
    <div id="sheet-image" class="sheet-image">
        <img src="<?= IMAGE_PATH . '/contact.jpg' ?>" alt="contact"/>
    </div>

    <div class="sheet-title"><h1>Contact</h1></div>
    <section>
        <h2>Mon message</h2>
        <form class="contact-form" method="POST" enctype="multipart/form-data">

            <label for="contact_name">Nom</label>
            <input type="text" id="contact_name" name="contact_name" placeholder="Nom*" value="<?= htmlentities( $contact_name ) ?>">

            <label for="contact_forname">Prénom</label>
            <input type="text" id="contact_forname" name="contact_forname" placeholder="Prénom*" value="<?= htmlentities( $contact_forname ) ?>">

            <label for="contact_email">Email</label>
            <input type="text" id="contact_email" name="contact_email" placeholder="Email*" value="<?= htmlentities( $contact_email ) ?>">

            <label for="contact_message">Message</label>
            <textarea id="contact_message" name="contact_message" placeholder="Message*"><?= htmlentities( $contact_message ) ?></textarea>

            <div class="contact-form-button">
                <button type="submit" class="button button-normal" name="action" value="send">Envoyer</button>
            </div>

        </form>
    </section>

</div>