<!DOCTYPE html>
<html lang="fr">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="<?= CSS_PATH ?>/style.css" />
        <script src="<?= JS_PATH ?>/jquery-2.2.3.min.js"></script>
        <script src="<?= JS_PATH ?>/main.js"></script>
        <script src="<?= JS_PATH ?>/ec-svg-icon/ec-svg-icon1.0.js"></script>
        <script src="<?= JS_PATH ?>/ec-gallery/ec-gallery1.0.js"></script>
        <script src="<?= JS_PATH ?>/ec-gallery/config-ec-gallery.js"></script>
        <title><?= htmlentities( $SETTINGS->findByName('short-name')->getValue() ) ?></title>
    </head>

    <body>

        <?php require("apps/header.php"); ?>
        <?php require("apps/content.php"); ?>
        <?php require("apps/footer.php"); ?>

    </body>
</html>